In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

/var/folders/y4/6_3sgdc945dcscpnt6p8q7100000gn/T/ipykernel_74965/4240260412.py:4: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport


In [3]:
df = pd.read_csv("advertising.csv")

In [4]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [5]:
df.shape

(200, 4)

In [8]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [10]:
pf = ProfileReport(df)

In [12]:
pf.to_widgets() # Gives the same dashboard as pandas profiling bur=t in structured manner or in widgets format

In [13]:
# save the dashboard as test.html file
pf.to_file('test.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [19]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [28]:
x = df[["TV"]] # make it 2d since 2d data is expected in fit() function.
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [29]:
y = df.Sales
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

Observation:- It is same as y = mx+c here it is sales = m(TV)+C

In [30]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()

In [32]:
# By doing this we are getting the optimal value of m and c
linear.fit(x,y)

LinearRegression()

In [33]:
# intercept means value of c
linear.intercept_


6.9748214882298925

In [34]:
# coefficient means value of m
linear.coef_

array([0.05546477])

In [49]:
# Save the model. We can share this model to anyone and the person can predict the o/p using this model without any training.
file  = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

### Prediction using pickle file

In [42]:
linear.predict([[45]])  # By Default it takes 2d i/p. Function is written that way.

/Users/madhu/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

Observation:- For TV advertisement if we spend $ 45 then sales will be 9.4.

In [43]:
# Prediction for multiple values
l = [4,5,6,7,89,34,45,67,23]

In [44]:
for i in l:
    print(linear.predict([[i]]))

[7.19668057]
[7.25214534]
[7.30761011]
[7.36307488]
[11.91118606]
[8.86062368]
[9.47073616]
[10.69096111]
[8.25051121]


/Users/madhu/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/madhu/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/madhu/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/madhu/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/madhu/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/madhu/opt/anaconda3/lib

### Do the prediction on pickle file


In [46]:
# Load the pickle file
saved_model = pickle.load(open(file,'rb'))

In [48]:
# Predict the sales from saved_model
saved_model.predict([[45]])

/Users/madhu/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

## Check the Accuracy

In [50]:
linear.score(x,y)

0.8121757029987414